### ISSUE TITLE
Texto sobre cookies

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/miciudad2#22]
El texto dice: "Este sitio web utiliza cookies propias y de terceros para mejorar la experiencia de navegación, y ofrecer contenidos y servicios de interés. Al continuar la navegación entendemos que se acepta nuestra política de cookies. Para más información consulta aquí."

¿Hay una forma de modificarla por medio de la interfaz administrativa?

**Comment by diegocrzt** [comment]
Este exto está dentro del código del core, solo puede ser cambiado ahí

**Comment by diegocrzt** [comment]
Por cierto la clave de internacionalización de esto es 

**layouts.decidim.cookie_warning.description_html**

Podríamos agregar la clave a nuestro archivo de internacionalización para sobreescribir su contenido

https://github.com/TEDICpy/miciudad2/blob/development/config/locales/es.yml


```yml
es:
    layouts:
        decidim:
          cookie_warning:
            description_html: Algún mensaje genial sobre las cookies con el %{link} de terminos y condiciones.
```

Bastaría definir ese texto
